version: '3.8'
services:
  rss-persistor:
    # enable for dev environment
    # build:
    #   dockerfile: Dockerfile_dev
    # volumes:
    #   - ./src:/var/www/html:ro
    # ports:
    #   - "127.0.0.1:8080:80"
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - rss-persistor
  mariadb:
    image: mariadb
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .env
    volumes:
      - ./mariadb:/var/lib/mysql:rw
    networks:
      - rss-persistor
networks:
  rss-persistor: